package:
  name: scippwidgets
  version: {{GIT_DESCRIBE_TAG}}

source:
  path: ..

requirements:
  build:
    - python {{ python }}
  run:
    - python {{ python }}
    - scipp
    - ipywidgets
    - matplotlib
    - ipyfilechooser

test:
  import:
    - scippwidgets
    - scippwidgets.inputs
    - scippwidgets.validators
    - scippwidgets.widgets
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - python -m pytest -v

build:
  number: {{environ.get('GIT_DESCRIBE_NUMBER', 0)}}

about:
  home: https://github.com/scipp/scippwidgets
  license: GPLv3
  summary: ipywidget wrappers for scipp
  description: ipywidget wrappers for scipp
  dev_url: https://github.com/scipp/scippwidgets
  doc_url:
